/** City names from the legacy data/raw/City.json export, sorted alphabetically. */
export const LEGACY_CITIES: readonly string[] = [
  "Akkaraipattu",
  "Akuressa",
  "Aluthgama",
  "Ambalangoda",
  "Ampara",
  "Ampitiya",
  "Angoda",
  "Anuradhapura",
  "Arugam Bay",
  "Athurugiriya",
  "Avissawella",
  "Badulla",
  "Balangoda",
  "Bandarawela",
  "Battaramulla",
  "Batticaloa",
  "Bentota",
  "Beruwala",
  "Boralesgamuwa",
  "Chilaw",
  "Colombo 01",
  "Colombo 02",
  "Colombo 03",
  "Colombo 04",
  "Colombo 05",
  "Colombo 06",
  "Colombo 07",
  "Colombo 08",
  "Colombo 09",
  "Colombo 10",
  "Colombo 11",
  "Colombo 12",
  "Colombo 13",
  "Colombo 14",
  "Colombo 15",
  "Dambadeniya",
  "Dambulla",
  "Dehiwala",
  "Divulapitiya",
  "Diyatalawa",
  "Ella",
  "Embilipitiya",
  "Ethul Kotte",
  "Galle",
  "Gampaha",
  "Gampola",
  "Hambantota",
  "Hanwella",
  "Haputale",
  "Hatton",
  "Hikkaduwa",
  "Hiriketiya",
  "Hokandara",
  "Homagama",
  "Ja-ela",
  "Jaffna",
  "Kadawatha",
  "Kaduwela",
  "Kalmunai",
  "Kalpitiya",
  "Kalubowila",
  "Kalutara",
  "Kandana",
  "Kandy",
  "Katugastota",
  "Katunayake",
  "Kegalle",
  "Kelaniya",
  "Kesbewa",
  "Kiribathgoda",
  "Kirindiwela",
  "Kithulgala",
  "Kohuwala",
  "Kollupitiya",
  "Kolonnawa",
  "Koswatte",
  "Kottawa",
  "Kotte",
  "Kuliyapitiya",
  "Kurunegala",
  "Madiwela",
  "Mahabage",
  "Maharagama",
  "Malabe",
  "Mannar",
  "Matale",
  "Matara",
  "Mawanella",
  "Meegoda",
  "Meerigama",
  "Minuwangoda",
  "Mirigama",
  "Mirissa",
  "Monaragala",
  "Moratuwa",
  "Mt. Lavinia",
  "Narammala",
  "Nawala",
  "Negombo",
  "Nugegoda",
  "Nuwara Eliya",
  "Other",
  "Pamankada",
  "Panadura",
  "Pannipitiya",
  "Pelawatta",
  "Peliyagoda",
  "Pepiliyana",
  "Piliyandala",
  "Polonnaruwa",
  "Pottuvil",
  "Puttalam",
  "Ragama",
  "Rajagiriya",
  "Rambukkana",
  "Ratmalana",
  "Ratnapura",
  "Seeduwa",
  "Seethawaka",
  "Tangalle",
  "Thalahena",
  "Thalawathugoda",
  "Tissamaharama",
  "Trincomalee",
  "Uswetakeiyawa",
  "Vavuniya",
  "Veyangoda",
  "Wadduwa",
  "Wattala",
  "Weligama",
  "Welisara",
  "Wellawaya",
];
