/**
 * Builds supabase/migrations/0032_apartment_complex_cleanup.sql from the live legacy
 * "Apartment Complexes" table and the NEW apartment_complexes rows (read-only).
 * Usage: npx tsx scripts/migrate/complex-cleanup-sql.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import {
  COMPLEX_ALIASES,
  COMPLEX_GROUPS,
  COMPLEX_PLACEHOLDERS,
  cleanLegacyComplex,
  complexNameResolver,
} from './complexes.js';
import { loadEnvFile } from './load-env.js';

loadEnvFile();
loadEnvFile('.env.local');

type Row = Record<string, unknown>;

const OUT = path.join(process.cwd(), 'supabase', 'migrations', '0032_apartment_complex_cleanup.sql');

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v || v.startsWith('REPLACE_ME_')) throw new Error(`Missing or placeholder ${name}`);
  return v;
}

async function fetchAll(sb: SupabaseClient, table: string, select: string): Promise<Row[]> {
  const all: Row[] = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await sb.from(table).select(select).range(from, from + 999);
    if (error) throw new Error(`${table}: ${error.message}`);
    all.push(...((data ?? []) as unknown as Row[]));
    if (!data || data.length < 1000) return all;
  }
}

const lit = (v: string | null) => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const arr = (a: string[]) => (a.length ? `array[${a.map(lit).join(', ')}]::text[]` : `'{}'::text[]`);

async function main(): Promise<void> {
  const legacy = createClient(requireEnv('LEGACY_SUPABASE_URL'), requireEnv('LEGACY_SUPABASE_SERVICE_ROLE_KEY'), {
    auth: { persistSession: false },
  });
  const next = createClient(requireEnv('SUPABASE_URL'), requireEnv('SUPABASE_SERVICE_ROLE_KEY'), {
    auth: { persistSession: false },
  });
  const [legacyRows, dbRows] = await Promise.all([
    fetchAll(legacy, 'Apartment Complexes', '*'),
    fetchAll(next, 'apartment_complexes', 'name'),
  ]);

  const complexes = new Map<string, ReturnType<typeof cleanLegacyComplex>>();
  for (const r of legacyRows) {
    const c = cleanLegacyComplex(r);
    if (c.name && !complexes.has(c.name.toLowerCase())) complexes.set(c.name.toLowerCase(), c);
  }
  const resolve = complexNameResolver([...complexes.values()].map((c) => c.name));
  const known = new Set([...complexes.values()].map((c) => c.name).concat(Object.keys(COMPLEX_GROUPS)));

  const merges = new Map<string, [string, string | null]>();
  const addMerge = (from: string, to: string | null) => merges.set(from.toLowerCase(), [from, to]);
  for (const from of Object.keys(COMPLEX_ALIASES)) addMerge(from, resolve(from));
  for (const p of COMPLEX_PLACEHOLDERS) addMerge(p, null);
  const unknown: string[] = [];
  for (const r of dbRows) {
    const name = String(r.name);
    const target = resolve(name);
    if (target !== null && !known.has(target)) unknown.push(name);
    else if (target !== name) addMerge(name, target);
  }
  if (unknown.length) {
    throw new Error(`Unclassified complex names in the new DB (add to complexes.ts): ${unknown.join(', ')}`);
  }

  const values = [...complexes.values()]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(
      (c) =>
        `  (${lit(c.name)}, ${lit(c.location)}, ${arr(c.amenities)}, ${lit(c.added_by)}, ${lit(c.address)}, ` +
        `${c.built_year ?? 'null'}, coalesce(${lit(c.created_at)}::timestamptz, now()))`,
    );
  const groups = Object.entries(COMPLEX_GROUPS).map(([n, loc]) => `  (${lit(n)}, ${lit(loc)})`);
  const mergeRows = [...merges.values()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([from, to]) => `  (${lit(from)}, ${lit(to)})`);

  const sql = `-- Apartment complexes: load the legacy "Apartment Complexes" table (location,
-- amenities, added by, address, built year), keep development-level names used on
-- listings (Havelock City, Cinnamon Life, ...), merge old/free-typed listing names into
-- the legacy name, and drop placeholders ("Any", "Other", "No Name").
-- Generated by scripts/migrate/complex-cleanup-sql.ts on ${new Date().toISOString().slice(0, 10)}.

begin;

alter table public.apartment_complexes add column if not exists address text;
alter table public.apartment_complexes add column if not exists built_year integer;

insert into public.apartment_complexes (name, location, amenities, added_by, address, built_year, created_at)
values
${values.join(',\n')}
on conflict (name) do update set
  location = coalesce(excluded.location, apartment_complexes.location),
  amenities = case when cardinality(excluded.amenities) > 0 then excluded.amenities else apartment_complexes.amenities end,
  added_by = coalesce(excluded.added_by, apartment_complexes.added_by),
  address = coalesce(excluded.address, apartment_complexes.address),
  built_year = coalesce(excluded.built_year, apartment_complexes.built_year),
  created_at = least(apartment_complexes.created_at, excluded.created_at);

insert into public.apartment_complexes (name, location)
values
${groups.join(',\n')}
on conflict (name) do update set
  location = coalesce(apartment_complexes.location, excluded.location);

-- from_name -> to_name (null = no complex). Matched case-insensitively.
create temp table complex_merge (from_name text primary key, to_name text) on commit drop;
insert into complex_merge (from_name, to_name)
values
${mergeRows.join(',\n')};

alter table public.properties disable trigger properties_set_updated_at;

update public.properties p
set apartment_complex_id = t.id
from complex_merge m
join public.apartment_complexes f on lower(f.name) = lower(m.from_name)
left join public.apartment_complexes t on t.name = m.to_name
where p.apartment_complex_id = f.id
  and f.name is distinct from m.to_name;

alter table public.properties enable trigger properties_set_updated_at;

delete from public.apartment_complexes c
using complex_merge m
where lower(c.name) = lower(m.from_name)
  and c.name is distinct from m.to_name;

commit;
`;
  fs.writeFileSync(OUT, sql, 'utf8');
  console.log(
    JSON.stringify(
      {
        legacy_complexes: complexes.size,
        groups: groups.length,
        merge_rules: mergeRows.length,
        db_names_merged_now: dbRows.filter((r) => merges.has(String(r.name).toLowerCase())).length,
        out: path.relative(process.cwd(), OUT),
      },
      null,
      2,
    ),
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
